# Configuration SonarCloud — CamwaterApp
sonar.projectKey=NaelleNangmo_kaba-delivery-backend
sonar.organization=naellenangmo
sonar.projectName=CamwaterApp — API Gestion Eau
sonar.projectVersion=1.0

sonar.sources=.
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,public/**,*.sql,*.js

# PHP
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=test-report.xml
